#!/usr/bin/env python3

USER_AGENT = "Passive-Lab-Exposure-Scanner/1.1"
MAX_BODY_READ = 1024 * 256

EXACT_RULES = [
    {
        "id": "env_exposure",
        "paths": ["/.env", "/config/.env"],
        "status": [200],
        "body": [
            r"(?mi)^APP_ENV=",
            r"(?mi)^APP_KEY=",
            r"(?mi)^DB_PASSWORD=",
            r"(?mi)^MAIL_PASSWORD=",
            r"(?mi)^DB_HOST=",
            r"(?mi)^JWT_SECRET=",
            r"(?mi)^AWS_SECRET_ACCESS_KEY=",
            r"(?mi)^STRIPE_SECRET=",
            r"(?mi)^VERCEL_",
            r"(?mi)^NETLIFY_",
        ],
        "min": 2,
        "remediation": "`.env` ve benzeri secret dosyalarını web root dışına taşı, web sunucuda erişimi engelle, sızmış tüm secretları rotate et.",
        "next_step": "Nginx/Apache deny rule ekle ve deploy pipeline'a secret scan koy.",
    },
    {
        "id": "env_example_exposure",
        "paths": ["/.env.example", "/.env.dist", "/.env.sample"],
        "status": [200],
        "body": [
            r"(?mi)^APP_ENV=",
            r"(?mi)^DB_HOST=",
            r"(?mi)^DB_PASSWORD=",
            r"(?mi)^MAIL_HOST=",
        ],
        "min": 1,
        "remediation": "Örnek env dosyalarında gerçek credential bırakma; gerekiyorsa sadece placeholder kullan.",
        "next_step": "Repo ve deploy artefact'larını gözden geçir.",
    },
    {
        "id": "git_config_exposure",
        "paths": ["/.git/config"],
        "status": [200],
        "body": [r"(?m)^\[core\]", r'(?m)^\[remote "origin"\]'],
        "min": 1,
        "remediation": "`.git` dizinini public erişimden çıkar, gerekiyorsa web server deny rule uygula.",
        "next_step": "Repo geçmişinde secret varsa rotate et ve erişim loglarını kontrol et.",
    },
    {
        "id": "phpinfo_exposure",
        "paths": ["/phpinfo.php"],
        "status": [200],
        "body": [r"phpinfo\(\)", r"PHP Version", r"Loaded Configuration File", r"DOCUMENT_ROOT"],
        "min": 1,
        "remediation": "`phpinfo()` dosyasını kaldır veya yalnızca iç ağdan erişilebilir yap.",
        "next_step": "PHP modülleri, pathler ve config sızıntısı olup olmadığını gözden geçir.",
    },
    {
        "id": "config_php_exposure",
        "paths": ["/config.php", "/includes/config.php", "/app/config.php"],
        "status": [200],
        "body": [r"(?i)db_host", r"(?i)db_name", r"(?i)db_user", r"(?i)db_pass", r"(?i)password"],
        "min": 2,
        "remediation": "Config dosyalarını public path'ten kaldır, web server deny uygula.",
        "next_step": "DB credential'larını rotate et.",
    },
    {
        "id": "web_config_exposure",
        "paths": ["/web.config", "/Web.config"],
        "status": [200],
        "body": [r"(?i)connectionString", r"(?i)<connectionStrings>", r"(?i)providerName"],
        "min": 1,
        "remediation": "`web.config` ve benzeri config dosyalarını public erişime kapat.",
        "next_step": "Connection string'lerdeki kimlik bilgilerini yenile.",
    },
    {
        "id": "ini_conf_exposure",
        "paths": ["/config.ini", "/settings.ini", "/app.ini", "/database.ini", "/config.conf", "/database.conf", "/db.conf"],
        "status": [200],
        "body": [r"(?i)smtp_pass", r"(?i)db_host", r"(?i)db_user", r"(?i)db_password", r"(?i)password\s*="],
        "min": 1,
        "remediation": "INI/CONF yapılandırmalarını public dizinden kaldır.",
        "next_step": "SMTP ve DB parolalarını rotate et.",
    },
    {
        "id": "log_exposure",
        "paths": [
            "/storage/logs/laravel.log",
            "/laravel.log",
            "/error.log",
            "/logs/error.log",
            "/apex_up.log",
        ],
        "status": [200],
        "body": [
            r"Authorization",
            r"password",
            r"token",
            r"email=",
            r"Set-Cookie",
            r"Stack trace",
            r"Fatal error",
            r"PHP Warning",
            r"PHP Notice",
            r"Warning: mysqli_connect\(\)",
            r"verifyMercadoPago",
            r"get_payment_info",
            r"get_merchant_order",
            r"last_four_digits",
            r"New Test User",
        ],
        "min": 1,
        "remediation": "Log dosyalarını public erişimden çıkar, log redaction uygula, hassas verileri loglamayı bırak.",
        "next_step": "Loglarda geçen token, parola, ödeme ve test hesap bilgilerini yenile.",
    },
    {
        "id": "sql_dump_exposure",
        "paths": ["/db.sql", "/database.sql", "/dump.sql", "/backup.sql"],
        "status": [200],
        "body": [r"-- Dump completed", r"phpMyAdmin SQL Dump", r"CREATE TABLE", r"INSERT INTO"],
        "min": 1,
        "remediation": "SQL dump dosyalarını public alandan kaldır.",
        "next_step": "Dump içeriğinde kullanıcı/veri varsa olay müdahale süreci başlat.",
    },
    {
        "id": "swagger_redoc_graphql",
        "paths": [
            "/swagger", "/swagger-ui", "/swagger-ui.html", "/api-docs",
            "/v1/api-docs", "/v2/api-docs", "/redoc",
            "/graphql", "/graphql/playground",
            "/openapi.json", "/swagger.json", "/swagger.yaml"
        ],
        "status": [200],
        "title": [r"Swagger UI", r"ReDoc", r"GraphQL Playground"],
        "body": [r"openapi", r"swagger", r"__schema", r"graphql"],
        "min": 1,
        "remediation": "API dokümantasyonunu gerekiyorsa auth arkasına al veya iç ağ ile sınırla.",
        "next_step": "Dokümanda hassas endpoint, test credential veya internal host sızıntısı var mı kontrol et.",
    },
    {
        "id": "symfony_profiler",
        "paths": ["/_profiler"],
        "status": [200],
        "title": [r"Symfony Profiler"],
        "min": 1,
        "remediation": "Profiler'ı production'da kapat.",
        "next_step": "Debug mode ve stack trace sızıntılarını kontrol et.",
    },
    {
        "id": "laravel_horizon",
        "paths": ["/horizon/dashboard"],
        "status": [200],
        "title": [r"Laravel Horizon"],
        "min": 1,
        "remediation": "Horizon erişimini auth ve IP allowlist ile sınırla.",
        "next_step": "Queue ve job metadatasında hassas veri var mı bak.",
    },
    {
        "id": "laravel_debugbar",
        "paths": ["/_debugbar"],
        "status": [200, 301, 302, 403],
        "body": [r"Laravel", r"Debugbar"],
        "min": 1,
        "remediation": "Laravel Debugbar'ı production'da devre dışı bırak.",
        "next_step": "APP_DEBUG ayarını false yap ve cache temizle.",
    },
    {
        "id": "laravel_ignition",
        "paths": ["/_ignition/execute-solution"],
        "status": [200, 401, 403, 405],
        "body": [r"ignition", r"solution", r"Laravel"],
        "min": 1,
        "remediation": "Ignition'ı production ortamında kapat veya erişimi kısıtla.",
        "next_step": "Framework sürümünü ve debug modunu doğrula.",
    },
    {
        "id": "spring_actuator",
        "paths": ["/actuator", "/actuator/health", "/actuator/env", "/actuator/metrics", "/actuator/prometheus"],
        "status": [200],
        "body": [r'"_links"', r'"health"', r'"status"', r'"names"', r"jvm_", r"process_"],
        "min": 1,
        "remediation": "Actuator endpoint'lerini auth arkasına al veya kapat.",
        "next_step": "Özellikle `/actuator/env` ve `/actuator/metrics` erişimlerini kapat.",
    },
    {
        "id": "server_status",
        "paths": ["/server-status", "/nginx_status"],
        "status": [200],
        "body": [r"Apache Server Status", r"Server Version", r"Active connections", r"server accepts handled requests"],
        "min": 1,
        "remediation": "Status endpoint'lerini public erişime kapat.",
        "next_step": "Yalnızca loopback veya iç ağdan erişim ver.",
    },
    {
        "id": "test_connection_panel",
        "paths": ["/admin/test-connection", "/ping?host=127.0.0.1", "/debug/echo", "/api/debug"],
        "status": [200, 401, 403],
        "body": [r"test connection", r"database connection", r"smtp connection", r"dump", r"debug", r"echo"],
        "min": 1,
        "remediation": "Debug/test endpoint'lerini production'dan kaldır veya auth arkasına al.",
        "next_step": "Sunucu tarafı dış istek yapan endpoint'leri kod incelemesine sok.",
    },
    {
        "id": "phpmyadmin_panel",
        "paths": ["/phpmyadmin", "/phpMyAdmin"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"phpMyAdmin"],
        "body": [r"phpMyAdmin"],
        "min": 1,
        "remediation": "phpMyAdmin'i public erişimden çıkar veya çok sıkı erişim kontrolü koy.",
        "next_step": "Varsayılan path'i kaldır, MFA/VPN/IP kısıtı uygula.",
    },
    {
        "id": "adminer_panel",
        "paths": ["/adminer.php", "/adminer"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"Adminer"],
        "body": [r"Adminer"],
        "min": 1,
        "remediation": "Adminer dosyasını production'dan kaldır.",
        "next_step": "Sunucuda bırakıldıysa tek kullanımlık bakım erişimi modeline geç.",
    },
    {
        "id": "webmin_panel",
        "paths": ["/webmin"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"Webmin"],
        "body": [r"Webmin"],
        "min": 1,
        "remediation": "Webmin panelini public ağdan ayır.",
        "next_step": "VPN veya IP allowlist zorunlu yap.",
    },
    {
        "id": "jenkins_panel",
        "paths": ["/jenkins", "/jenkins/login", "/script"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"Dashboard \[Jenkins\]", r"Script Console"],
        "body": [r"Jenkins", r"Groovy script"],
        "min": 1,
        "remediation": "Jenkins'i public erişimden çıkar, script console'u kapat.",
        "next_step": "Anonymous read ve script yetkilerini denetle.",
    },
    {
        "id": "gitlab_panel",
        "paths": ["/gitlab"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"Sign in · GitLab"],
        "min": 1,
        "remediation": "GitLab panelini iç ağa taşı veya erişimi sınırla.",
        "next_step": "Public register/SSO/2FA ayarlarını kontrol et.",
    },
    {
        "id": "sonarqube_panel",
        "paths": ["/sonarqube"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"SonarQube"],
        "min": 1,
        "remediation": "SonarQube'a public erişimi kapat.",
        "next_step": "Project browse izinlerini denetle.",
    },
    {
        "id": "nexus_panel",
        "paths": ["/nexus/"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"Nexus Repository Manager"],
        "min": 1,
        "remediation": "Nexus erişimini ağ seviyesinde sınırla.",
        "next_step": "Anonymous artifact erişimini gözden geçir.",
    },
    {
        "id": "rundeck_panel",
        "paths": ["/rundeck"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"Welcome to Rundeck"],
        "min": 1,
        "remediation": "Rundeck'i public erişime kapat.",
        "next_step": "Project/job yetkilerini ve webhook'ları incele.",
    },
    {
        "id": "teamcity_panel",
        "paths": ["/teamcity"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"TeamCity"],
        "min": 1,
        "remediation": "TeamCity'i iç ağ/VPN arkasına al.",
        "next_step": "Guest user ve token politikalarını kontrol et.",
    },
    {
        "id": "kibana_or_grafana_or_portainer_or_zabbix",
        "paths": ["/kibana", "/zabbix", "/portainer", "/grafana"],
        "status": [200, 301, 302, 401, 403],
        "title": [r"Kibana", r"Grafana", r"Portainer", r"Zabbix"],
        "body": [r"Kibana", r"Grafana", r"Portainer", r"Zabbix"],
        "min": 1,
        "remediation": "Yönetim panellerini public erişime kapat veya güçlü erişim kontrolü uygula.",
        "next_step": "SSO, MFA, IP allowlist ve audit logları kontrol et.",
    },
    {
        "id": "rails_routes",
        "paths": ["/rails/info/routes"],
        "status": [200, 401, 403],
        "body": [r"Ruby on Rails"],
        "min": 1,
        "remediation": "Rails info routes/debug sayfalarını production'da kapat.",
        "next_step": "Debug route exposure ve sensitive path disclosure kontrol et.",
    },
    {
        "id": "h2_console",
        "paths": ["/h2-console/login.jsp"],
        "status": [200, 401, 403],
        "title": [r"H2 Console"],
        "body": [r"H2 Console"],
        "min": 1,
        "remediation": "H2 console'u production ortamından kaldır.",
        "next_step": "Embedded DB kullanımını ve erişim politikalarını incele.",
    },
    {
        "id": "docker_or_k8s_or_secrets",
        "paths": [
            "/docker-compose.yml",
            "/.docker/config.json",
            "/values.yaml",
            "/kube/config",
            "/config.json",
            "/secrets",
            "/secrets.json",
            "/credentials.json",
        ],
        "status": [200],
        "body": [
            r"services:",
            r"container_name",
            r"kubernetes.io",
            r"aws_access_key_id",
            r"AWS_SECRET_ACCESS_KEY",
            r"gcp_project_id",
            r"api_key",
            r"access_token",
        ],
        "min": 1,
        "remediation": "Container/orchestration ve secret dosyalarını public erişime kapat.",
        "next_step": "Cloud key'leri ve service account'ları rotate et.",
    },
    {
        "id": "sourcemap_exposure",
        "paths": ["/app.js.map", "/main.js.map", "/bundle.js.map", "/static/js/main.js.map", "/assets/index.js.map"],
        "status": [200],
        "body": [r'"version"\s*:\s*3', r'"sources"\s*:', r'"mappings"\s*:'],
        "min": 1,
        "remediation": "Production'da sourcemap yayınlama veya ayrı korumalı depoda tut.",
        "next_step": "Kaynak kod yolu, endpoint ve secret kalıntısı var mı kontrol et.",
    },
    {
        "id": "js_secret_exposure_hint",
        "paths": ["/app.js", "/main.js", "/bundle.js", "/static/js/main.js", "/assets/index.js"],
        "status": [200],
        "body": [
            r"eyJ[a-zA-Z0-9_\-]{10,}\.[a-zA-Z0-9_\-]{10,}\.[a-zA-Z0-9_\-]{5,}",
            r"(?i)\baccess_token\b",
            r"(?i)\bapi_key\b",
            r"(?i)\bclient_secret\b",
            r"(?i)\bpaypal_client_id\b",
            r"(?i)\bSTRIPE_SECRET\b",
        ],
        "min": 1,
        "remediation": "Client-side bundle'da secret tutma; server-side vault/secrets manager kullan.",
        "next_step": "Bundle diff ve CI secret scan ekle.",
    },
    {
        "id": "directory_listing",
        "paths": ["/backup/", "/backups/", "/logs/", "/storage/", "/config/", "/private/", "/secure/", "/source/"],
        "status": [200],
        "title": [r"Index of"],
        "body": [r"Index of /", r"Parent Directory", r"Index of"],
        "min": 1,
        "remediation": "Directory listing'i kapat.",
        "next_step": "Açık listelenen tüm dosyaları tek tek gözden geçir.",
    },
]

BACKUP_BASES = [
    "/.env",
    "/config/.env",
    "/.env.example",
    "/config.php",
    "/includes/config.php",
    "/app/config.php",
    "/db.sql",
    "/database.sql",
    "/dump.sql",
    "/backup.sql",
    "/site_backup",
    "/db_backup",
    "/archive",
    "/web.config",
    "/config.ini",
    "/database.ini",
    "/db.conf",
    "/credentials",
    "/source",
    "/private",
]

BACKUP_SUFFIXES = [
    ".zip",
    ".tar.gz",
    ".gz",
    ".sql",
    ".bak",
    ".old",
    ".copy",
    ".tmp",
    ".save",
    ".swp",
    ".orig",
    "~",
    ".backup",
]